### ISSUE TITLE
[Feature]: 개발용 로그인 회원가입 API 개발

### ISSUE THREAD

**Issue by InHyeok-J** [MoyeoRun/MoyeoRun_Spring#4]
## 기능 설명

- 개발용 로그인 및 회원가입 API 개발 => ADMIN 용으로 처리
- 기존 코드 리팩토링 사항 

## Tasks

- [x] 개발용 로그인 및 회원가입 API 개발 => ADMIN 으로 총 처리
- [x] auth domain -> user 로 변경
- [x] 로그인된 유저 커스텀 애노테이션 추가
