### ISSUE TITLE
[Feature]: 러닝 방 생성 및 조회 기능 구현

### ISSUE THREAD

**Issue by InHyeok-J** [MoyeoRun/MoyeoRun_Spring#8]
## 기능 설명

- 러닝 방 생성 
- 러닝 방 예약 -> 알림 테이블에 관리
- 러닝 방 예약 취소
- 러닝 방 참여 
- 러닝 방 참여 취소
- 러닝 방 조회 1개
- 메인페이지 러닝 방 리스트 조회
- 메인 페이지 현재 모집 중인 방 리스트 조회

## Tasks

- [x] 러닝 방 생성
- [x] 러닝 방 예약하기
- [x] 러닝 방 예약 취소
- [x] 러닝 방 참여하기
- [x] 러닝 방 참여 취소
- [x] 러닝 방 조회 1개
- [x] 메인페이지 러닝 방 리스트 조회 (실시간, 모집 중 )
- [x] 현재 참여중인 러닝 방 조회
- [x] NCP 배포 및 서버 마이그레이션
- [x] 러닝 방 자동 종료(임시)
